<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Surat Keterangan Domisili</title>
    <style>
        /* CSS untuk styling surat */
        body { font-family: 'Times New Roman', Times, serif; font-size: 12pt; line-height: 1.5; }
        .container { width: 80%; margin: auto; padding: 20px; }
        .header, .footer { text-align: center; }
        .kop-surat { text-align: center; margin-bottom: 20px; }
        .kop-surat img { width: 100px; height: auto; float: left; margin-right: 15px; }
        .kop-surat h4 { margin: 0; padding: 0; }
        .kop-surat p { margin: 0; padding: 0; font-size: 10pt; }
        .title { text-align: center; text-decoration: underline; margin: 20px 0; }
        .content { text-align: justify; margin-bottom: 30px; }
        .indent { text-indent: 40px; }
        .data-table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        .data-table td { padding: 5px 0; vertical-align: top; }
        .signature { width: 40%; float: right; text-align: center; margin-top: 30px; }
        .clearfix::after { content: ""; clear: both; display: table; }
    </style>
</head>
<body>
    <div class="container">
        <div class="kop-surat clearfix">
            {{-- <img src="{{ public_path('path/to/logo_desa.png') }}" alt="Logo Desa"> --}}
            <h4>PEMERINTAH KABUPATEN [NAMA KABUPATEN]</h4>
            <h4>KECAMATAN [NAMA KECAMATAN]</h4>
            <h3>DESA KUMANTAN</h3>
            <p>Alamat: Jl. Contoh No. 123, Kode Pos 12345</p>
            <hr style="border: 2px solid black;">
        </div>

        <div class="title">
            SURAT KETERANGAN DOMISILI<br>
            Nomor: {{ $permohonan->nomor_surat ?? '...' }}
        </div>

        <div class="content">
            <p class="indent">Yang bertanda tangan di bawah ini, Kepala Desa Kumantan Kecamatan [NAMA KECAMATAN] Kabupaten [NAMA KABUPATEN], dengan ini menerangkan bahwa:</p>

            <table class="data-table">
                <tr><td>Nama</td><td>:</td><td>{{ $permohonan->nama_pemohon }}</td></tr>
                <tr><td>NIK</td><td>:</td><td>{{ $permohonan->nik_pemohon }}</td></tr>
                <tr><td>Jenis Kelamin</td><td>:</td><td>{{ $permohonan->jenis_kelamin_pemohon }}</td></tr>
                <tr><td>Tempat/Tgl Lahir</td><td>:</td><td>{{ $permohonan->tempat_lahir_pemohon }}, {{ \Carbon\Carbon::parse($permohonan->tanggal_lahir_pemohon)->translatedFormat('d F Y') }}</td></tr>
                <tr><td>Kewarganegaraan</td><td>:</td><td>{{ $permohonan->kewarganegaraan_pemohon }}</td></tr>
                <tr><td>Agama</td><td>:</td><td>{{ $permohonan->agama_pemohon }}</td></tr>
                <tr><td>Pekerjaan</td><td>:</td><td>{{ $permohonan->pekerjaan_pemohon }}</td></tr>
                <tr><td>Status Perkawinan</td><td>:</td><td>{{ $permohonan->status_perkawinan_pemohon }}</td></tr>
                <tr><td>Alamat Asal</td><td>:</td><td>{{ $permohonan->alamat_asal_pemohon }}</td></tr>
                <tr><td>Alamat Sekarang</td><td>:</td><td>{{ $permohonan->alamat_sekarang_pemohon }}</td></tr>
            </table>

            <p class="indent">Berdasarkan data yang ada pada kami, nama tersebut di atas benar-benar berdomisili di Desa Kumantan.</p>

            <p class="indent">Surat keterangan ini dibuat sebagai kelengkapan {{ $permohonan->keperluan ?? '...' }} dan berlaku sejak tanggal dikeluarkan sampai dengan {{ $permohonan->tanggal_berlaku_sampai ?? '...' }}.</p>

            <p class="indent">Demikian surat keterangan ini dibuat untuk dapat dipergunakan sebagaimana mestinya.</p>
        </div>

        <div class="signature clearfix">
            Kumantan, {{ \Carbon\Carbon::now()->translatedFormat('d F Y') }}<br>
            Kepala Desa Kumantan<br><br><br><br>
            (Nama Kepala Desa)<br>
            <hr style="width: 80%; border-top: 1px solid black; margin: auto;">
            NIP. ............................ (jika ada)
        </div>

        <div class="footer" style="position: absolute; bottom: 20px; left: 0; right: 0;">
            <p>Generated by Sistem Informasi Layanan Desa Kumantan</p>
        </div>
    </div>
</body>
</html>